// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef VAULT_ALGORITHM_FSST_DICTIONARY_HPP
#define VAULT_ALGORITHM_FSST_DICTIONARY_HPP

#include <algorithm> // for std::clamp
#include <cstddef>
#include <cstdint>
#include <functional>
#include <iterator>
#include <memory>
#include <optional>
#include <ranges>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include <range/v3/range/conversion.hpp>
#include <range/v3/view/transform.hpp>

namespace vault::algorithm {

  /// @brief A lightweight, opaque handle to a string stored in an
  /// fsst_dictionary.
  ///
  /// @details
  /// An fsst_key is an 8-byte value that encodes the location of a string.
  /// It utilizes a "Small String Optimization" (SSO) scheme:
  /// - **Inline:** If the string is <= 7 bytes, the characters and length are
  ///   packed directly into the 64-bit integer. Dereferencing is effectively
  ///   free.
  /// - **Pointer:** If the string is > 7 bytes, the key stores an offset into
  ///   the dictionary's compressed data blob and the compressed length.
  struct fsst_key {
    std::uint64_t value;
    bool          operator==(const fsst_key&) const = default;
  };

  static_assert(sizeof(fsst_key) == 8, "fsst_key must be exactly 8 bytes");

  /// @brief A high-performance, compressed string dictionary based on FSST.
  ///
  /// @details
  /// The fsst_dictionary provides a read-only mapping from `fsst_key` to
  /// `std::string`. It is designed for high-throughput scenarios where memory
  /// bandwidth is a bottleneck.
  ///
  /// **Key Features:**
  /// - **FSST Compression:** Long strings are compressed using Fast Static
  /// Symbol Table (FSST),
  ///   typically achieving ~2x compression on text/URLs.
  /// - **Zero-Latency SSO:** Strings <= 7 bytes bypass the dictionary entirely
  /// and are
  ///   decoded directly from the `fsst_key` register.
  /// - **Cache Locality:** Compressed data is stored in a single contiguous
  /// blob, minimizing
  ///   cache misses compared to `std::vector<std::string>`.
  ///
  /// **Construction:**
  /// Use the static `build` factories to construct a dictionary. Construction
  /// is type-erased to support various input sources (Generators) and
  /// deduplication strategies.
  class fsst_dictionary {
  public:
    /// @brief Configuration for the compression training sample rate.
    /// Values must be in (0.0, 1.0]. Lower values speed up construction for
    /// large datasets.
    struct sample_ratio {
      float value = 1.0;
    };

    /// @brief Abstract configuration for compression effort (0-9).
    /// Level 9 implies 100% sampling; Level 0 implies 1/1024 sampling.
    struct compression_level {
      std::size_t value = 9;
    };

    /// @brief Generator for Views (Zero-Copy).
    /// @details
    /// Returns a view into **stable, existing memory**.
    /// - `std::nullopt` signals the end of the sequence.
    /// - The memory pointed to by the `string_view` must remain valid until
    /// `build` returns.
    using Generator = std::function<std::optional<std::string_view>()>;

    /// @brief Generator for R-Values (Ownership Transfer).
    /// @details
    /// Returns a string that the dictionary builder must take ownership of.
    /// - The builder will move these strings into an internal stable buffer
    /// before processing.
    /// - `std::nullopt` signals the end of the sequence.
    using RValueGenerator = std::function<std::optional<std::string>()>;

    /// @brief Deduplication callback strategy.
    /// @param s The string to look up or insert.
    /// @return A pair `{index, inserted}`. If `inserted` is true, the string is
    /// new.
    using Deduplicator =
      std::function<std::pair<std::uint64_t, bool>(std::string_view)>;

    /// @brief Pre-defined sampling ratios corresponding to compression levels
    /// 0-9.
    static constexpr inline sample_ratio const compression_levels[10] = {
      {1.0f / 1024.0f},
      {1.0f / 512.0f},
      {1.0f / 256.0f},
      {1.0f / 128.0f},
      {1.0f / 64.0f},
      {1.0f / 32.0f},
      {1.0f / 16.0f},
      {1.0f / 8.0f},
      {1.0f / 4.0f},
      {1.0f}};

    [[nodiscard]] fsst_dictionary();

    [[nodiscard]] fsst_dictionary(const fsst_dictionary&)     = default;
    [[nodiscard]] fsst_dictionary(fsst_dictionary&&) noexcept = default;

    fsst_dictionary& operator=(const fsst_dictionary&)     = default;
    fsst_dictionary& operator=(fsst_dictionary&&) noexcept = default;

    ~fsst_dictionary();

    /// @brief Decompresses and returns the string associated with the key.
    /// @param key A key previously generated by this dictionary.
    /// @return The decompressed string, or `std::nullopt` if the key is invalid
    /// (bounds check).
    /// @note For inline keys (<= 7 bytes), this does not access the dictionary
    /// memory.
    [[nodiscard]] std::optional<std::string> operator[](fsst_key key) const;

    [[nodiscard]] bool        empty() const;
    [[nodiscard]] std::size_t size_in_bytes() const;

    // --- Helpers for Key Generation ---

    /// @brief Checks if a string is small enough to fit inline in an fsst_key.
    /// @return true if s.size() <= 7.
    [[nodiscard]] static bool is_inline_candidate(std::string_view s) noexcept;

    /// @brief Creates an inline fsst_key from a small string.
    /// @pre s.size() <= 7
    /// @throws std::length_error if s.size() > 7.
    [[nodiscard]] static fsst_key make_inline_key(std::string_view s);

    /// @brief Converts an integer compression level (0-9) to a sampling ratio.
    [[nodiscard]] static constexpr inline auto level_to_ratio(
      compression_level level) -> sample_ratio
    {
      static constexpr auto max_compression_level =
        std::ranges::size(fsst_dictionary::compression_levels);

      auto const clamped_level =
        std::clamp(level.value, 0uz, max_compression_level - 1);

      return fsst_dictionary::compression_levels[clamped_level];
    }

    // --- Core Factories (View Based) ---

    /// @brief Builds a dictionary using a View Generator (Zero-Copy).
    /// @param gen Source of stable string_views.
    /// @param dedup Strategy for mapping strings to unique indices.
    /// @param emit_key Callback invoked for every input string with its
    /// generated key.
    /// @param ratio Sampling ratio for FSST training (default 1.0).
    [[nodiscard]] static auto build(Generator gen,
      Deduplicator                            dedup,
      std::function<void(fsst_key)>           emit_key,
      sample_ratio ratio = sample_ratio{1.}) -> fsst_dictionary;

    /// @brief Optimized build for unique inputs (skips deduplication).
    /// @param gen Source of stable string_views (must be unique).
    /// @param emit_key Callback invoked for every input string.
    /// @param ratio Sampling ratio.
    [[nodiscard]] static auto build_from_unique(Generator gen,
      std::function<void(fsst_key)>                       emit_key,
      sample_ratio ratio = sample_ratio{1.}) -> fsst_dictionary;

    /// @brief Convenience overload returning dictionary and vector of keys
    /// (Zero-Copy).
    [[nodiscard]] static auto build(
      Generator gen, Deduplicator dedup, sample_ratio ratio = sample_ratio{1.})
      -> std::pair<fsst_dictionary, std::vector<fsst_key>>;

    /// @brief Convenience overload returning dictionary and vector of keys from
    /// unique input.
    [[nodiscard]] static auto build_from_unique(
      Generator gen, sample_ratio ratio = sample_ratio{1.})
      -> std::pair<fsst_dictionary, std::vector<fsst_key>>;

    // --- R-Value Factories (String Based) ---

    /// @brief Builds a dictionary using an R-Value Generator (Ownership
    /// Transfer).
    /// @details Input strings are moved into an internal stable buffer before
    /// processing.
    /// @param gen Source of temporary strings.
    /// @param dedup Deduplication strategy.
    /// @param emit_key Callback for generated keys.
    [[nodiscard]] static auto build(RValueGenerator gen,
      Deduplicator                                  dedup,
      std::function<void(fsst_key)>                 emit_key,
      sample_ratio ratio = sample_ratio{1.}) -> fsst_dictionary;

    /// @brief Optimized build for unique R-Values.
    [[nodiscard]] static auto build_from_unique(RValueGenerator gen,
      std::function<void(fsst_key)>                             emit_key,
      sample_ratio ratio = sample_ratio{1.}) -> fsst_dictionary;

    /// @brief Convenience overload returning pair (R-Value/Buffered).
    [[nodiscard]] static auto build(RValueGenerator gen,
      Deduplicator                                  dedup,
      sample_ratio                                  ratio = sample_ratio{1.})
      -> std::pair<fsst_dictionary, std::vector<fsst_key>>;

    /// @brief Convenience overload returning pair from unique R-Values.
    [[nodiscard]] static auto build_from_unique(
      RValueGenerator gen, sample_ratio ratio = sample_ratio{1.})
      -> std::pair<fsst_dictionary, std::vector<fsst_key>>;

    // --- Compression Level Overloads ---

    [[nodiscard]] static inline auto build(Generator gen,
      Deduplicator                                   dedup,
      std::function<void(fsst_key)>                  emit_key,
      compression_level                              level) -> fsst_dictionary
    {
      return build(std::move(gen),
        std::move(dedup),
        std::move(emit_key),
        level_to_ratio(level));
    }

    [[nodiscard]] static inline auto build_from_unique(Generator gen,
      std::function<void(fsst_key)>                              emit_key,
      compression_level level) -> fsst_dictionary
    {
      return build_from_unique(
        std::move(gen), std::move(emit_key), level_to_ratio(level));
    }

    [[nodiscard]] static inline auto build(
      Generator gen, Deduplicator dedup, compression_level level)
      -> std::pair<fsst_dictionary, std::vector<fsst_key>>
    {
      return build(std::move(gen), std::move(dedup), level_to_ratio(level));
    }

    [[nodiscard]] static inline auto build_from_unique(
      Generator gen, compression_level level)
      -> std::pair<fsst_dictionary, std::vector<fsst_key>>
    {
      return build_from_unique(std::move(gen), level_to_ratio(level));
    }

    // --- Range Interface (Generalized) ---

    /// @brief Generic build from any Input Range.
    /// @details
    /// - **Optimization:** If `R` contains contiguous lvalues (e.g.,
    /// `vector<string>&`),
    ///   it uses the Zero-Copy path (View Generator).
    /// - **Fallback:** If `R` contains r-values or non-contiguous bytes (e.g.,
    /// `list<vector<char>>`),
    ///   it uses the R-Value path (buffering data internally).
    template <std::ranges::input_range R, typename... Args>
    [[nodiscard]] static auto build(R&& range, Args&&... args)
    {
      using ValueType = std::ranges::range_value_t<R>;
      using Reference = std::ranges::range_reference_t<R>;

      constexpr auto is_contiguous_lvalue =
        std::ranges::contiguous_range<ValueType>
        && std::is_lvalue_reference_v<Reference>;

      auto it  = std::ranges::begin(range);
      auto end = std::ranges::end(range);

      if constexpr (is_contiguous_lvalue) {
        // Path A: Zero Copy (Views)
        auto gen =
          Generator{[it, end]() mutable -> std::optional<std::string_view> {
            if (it == end) {
              return std::nullopt;
            }
            auto&& val = *it;
            ++it;
            return std::string_view{
              reinterpret_cast<const char*>(std::ranges::data(val)),
              std::ranges::size(val)};
          }};
        return build(std::move(gen), std::forward<Args>(args)...);

      } else {
        // Path B: R-Value (Buffering)
        auto gen =
          RValueGenerator{[it, end]() mutable -> std::optional<std::string> {
            if (it == end) {
              return std::nullopt;
            }
            auto&& val = *it;
            auto   s =
              std::string(reinterpret_cast<const char*>(std::ranges::data(val)),
                std::ranges::size(val));
            ++it;
            return s;
          }};
        return build(std::move(gen), std::forward<Args>(args)...);
      }
    }

    /// @brief Generic build from unique Input Range (skips deduplication).
    template <std::ranges::input_range R, typename... Args>
    [[nodiscard]] static auto build_from_unique(R&& range, Args&&... args)
    {
      using ValueType = std::ranges::range_value_t<R>;
      using Reference = std::ranges::range_reference_t<R>;

      constexpr auto is_contiguous_lvalue =
        std::ranges::contiguous_range<ValueType>
        && std::is_lvalue_reference_v<Reference>;

      auto it  = std::ranges::begin(range);
      auto end = std::ranges::end(range);

      if constexpr (is_contiguous_lvalue) {
        auto gen =
          Generator{[it, end]() mutable -> std::optional<std::string_view> {
            if (it == end) {
              return std::nullopt;
            }
            auto&& val = *it;
            ++it;
            return std::string_view{
              reinterpret_cast<const char*>(std::ranges::data(val)),
              std::ranges::size(val)};
          }};
        return build_from_unique(std::move(gen), std::forward<Args>(args)...);

      } else {
        auto gen =
          RValueGenerator{[it, end]() mutable -> std::optional<std::string> {
            if (it == end) {
              return std::nullopt;
            }
            auto&& val = *it;
            auto   s =
              std::string(reinterpret_cast<const char*>(std::ranges::data(val)),
                std::ranges::size(val));
            ++it;
            return s;
          }};
        return build_from_unique(std::move(gen), std::forward<Args>(args)...);
      }
    }

  private:
    class impl;
    std::shared_ptr<impl const> p_impl;

    [[nodiscard]] explicit fsst_dictionary(
      std::shared_ptr<impl const> implementation);

    [[nodiscard]] static auto compress_core(std::size_t count,
      std::size_t*                                      lens,
      unsigned char const**                             ptrs,
      float                                             sample_ratio)
      -> std::pair<std::shared_ptr<impl>, std::vector<fsst_key>>;
  };
} // namespace vault::algorithm

#endif // VAULT_ALGORITHM_FSST_DICTIONARY_HPP
