# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Continuous Integration Tests

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * *'

jobs:
  preset-test:
    strategy:
      fail-fast: false
      matrix:
        presets:
          - preset: "gcc-debug"
            platform: "ubuntu-latest"
          - preset: "gcc-release"
            platform: "ubuntu-latest"
          - preset: "appleclang-debug"
            platform: "macos-latest"
          - preset: "appleclang-release"
            platform: "macos-latest"
          - preset: "msvc-debug"
            platform: "windows-latest"
          - preset: "msvc-release"
            platform: "windows-latest"
    name: "Preset: ${{ matrix.presets.preset }} on ${{ matrix.presets.platform }}"
    runs-on: ${{ matrix.presets.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
      - name: Setup MSVC
        if: startsWith(matrix.presets.platform, 'windows')
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Run preset
        run: cmake --workflow --preset ${{ matrix.presets.preset }}

  gtest-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - description: "Ubuntu GNU"
            os: ubuntu-latest
            toolchain: "cmake/gnu-toolchain.cmake"
          - description: "Ubuntu LLVM"
            os: ubuntu-latest
            toolchain: "cmake/llvm-toolchain.cmake"
          - description: "Windows MSVC"
            os: windows-latest
            toolchain: "cmake/msvc-toolchain.cmake"
          - description: "Macos Appleclang"
            os: macos-latest
            toolchain: "cmake/appleclang-toolchain.cmake"
        cpp_version: [17, 20, 23, 26]
        cmake_args:
          - description: "Default"
          - description: "TSan"
            args: "-DBEMAN_BUILDSYS_SANITIZER=TSan"
          - description: "MaxSan"
            args: "-DBEMAN_BUILDSYS_SANITIZER=MaxSan"
        include:
          - platform:
              description: "Ubuntu GCC"
              os: ubuntu-latest
              toolchain: "cmake/gnu-toolchain.cmake"
            cpp_version: 17
            cmake_args:
              description: "Werror"
              args: "-DCMAKE_CXX_FLAGS='-Werror=all -Werror=extra'"
          - platform:
              description: "Ubuntu GCC"
              os: ubuntu-latest
              toolchain: "cmake/gnu-toolchain.cmake"
            cpp_version: 17
            cmake_args:
              description: "Dynamic"
              args: "-DBUILD_SHARED_LIBS=on"
        exclude:
            # MSVC does not support thread sanitizer
          - platform:
              description: "Windows MSVC"
            cmake_args:
              description: "TSan"

    name: "Unit: ${{ matrix.platform.description }} ${{ matrix.cpp_version }} ${{ matrix.cmake_args.description }}"
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
      - name: Setup MSVC
        if: startsWith(matrix.platform.os, 'windows')
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      - name: Setup Macos
        if: startsWith(matrix.platform.os, 'macos')
        run: sudo chmod -R 777 /opt/
      - name: Print installed softwares
        shell: bash
        run: |
          echo "Build system:"
          cmake --version
          ninja --version
      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_CXX_STANDARD=${{ matrix.cpp_version }} -DCMAKE_TOOLCHAIN_FILE="${{ matrix.platform.toolchain }}" ${{ matrix.cmake_args.args }}
        env:
          CMAKE_GENERATOR: "Ninja Multi-Config"
      - name: Build Release
        run: |
          # Portable commands only
          cmake --build build --config Release --parallel --verbose
          cmake --build build --config Release --target all_verify_interface_header_sets
          cmake --install build --config Release --prefix /opt/beman.exemplar
          ls -R /opt/beman.exemplar
      - name: Test Release
        run: ctest --test-dir build --build-config Release
      - name: Build Debug
        run: |
          # Portable commands only
          cmake --build build --config Debug --parallel --verbose
          cmake --build build --config Debug --target all_verify_interface_header_sets
          cmake --install build --config Debug --prefix /opt/beman.exemplar
          ls -R /opt/beman.exemplar
      - name: Test Debug
        run: ctest --test-dir build --build-config Debug

  configuration-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        args:
          - name: "Disable build testing"
            arg: "-DBEMAN_EXEMPLAR_BUILD_TESTS=OFF"
          - name: "Disable example building"
            arg: "-DBEMAN_EXEMPLAR_BUILD_EXAMPLES=OFF"
          - name: "Enable shared libs?"
            arg: "-DBEMAN_EXEMPLAR_SHARED_LIBS=ON"
          - name: "Enable position-independent code?"
            arg: "-DBEMAN_EXEMPLAR_POSITION_INDEPENDENT_CODE=ON"
          - name: "Enable config-file package creation?"
            arg: "-DBEMAN_EXEMPLAR_CONFIG_FILE_PACKAGE=OFF"
          - name: "Specify config-file package version compatibility"
            arg: "-DBEMAN_EXEMPLAR_CONFIG_FILE_PACKAGE_COMPATIBILITY=SameMajorVersion"
          - name: "Specify the name of the target export variant to create"
            arg: "-DBEMAN_EXEMPLAR_TARGET_EXPORT_VARIANT=custom"
          - name: "Specify the name of the development install component"
            arg: "-DBEMAN_EXEMPLAR_DEVELOPMENT_INSTALL_COMPONENT=development"
          - name: "Specify the name of the runtime install component"
            arg: "-DBEMAN_EXEMPLAR_RUNTIME_INSTALL_COMPONENT=runtime"
          - name: "Override default library install directory"
            arg: "-DBEMAN_EXEMPLAR_INSTALL_LIBDIR=local/lib"
          - name: "Override default executable installation directory"
            arg: "-DBEMAN_EXEMPLAR_INSTALL_BINDIR=local/bin"
          - name: "Override default include install directory"
            arg: "-DBEMAN_EXEMPLAR_INSTALL_INCLUDEDIR=local/include"
          - name: "Override default CMake config-file package install directory"
            arg: "-DBEMAN_EXEMPLAR_INSTALL_INCLUDEDIR=local/lib/cmake/beman.exemplar"
          - name: "Override the default library suffix"
            arg: "-DBEMAN_EXEMPLAR_LIBRARY_SUFFIX=-custom"
    name: "CMake: ${{ matrix.args.name }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
      - name: Print installed softwares
        run: |
          cmake --version
          ninja --version
      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_CXX_STANDARD=17 ${{ matrix.args.arg }}
        env:
          CMAKE_GENERATOR: "Ninja Multi-Config"
      - name: Build Release
        run: |
          # Portable commands only
          cmake --build build --config Release --parallel --verbose
          cmake --build build --config Release --target all_verify_interface_header_sets
          cmake --install build --config Release --prefix /opt/beman.exemplar
          ls -R /opt/beman.exemplar
      - name: Build Debug
        run: |
          # Portable commands only
          cmake --build build --config Debug --parallel --verbose
          cmake --build build --config Debug --target all_verify_interface_header_sets
          cmake --install build --config Debug --prefix /opt/beman.exemplar
          ls -R /opt/beman.exemplar

  target-export-variant-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cases:
          - description: Default target export variant is static
            config: ~
            expected-variant: static
            expected-library: .a
          - description: Project-specific shared libs option has first priority
            config: -DBEMAN_EXEMPLAR_SHARED_LIBS=ON -DBEMAN_SHARED_LIBS=OFF -DSHARED_LIBS=OFF
            expected-variant: shared
            expected-library: .so
          - description: Project-specific shared libs option has first priority
            config: -DBEMAN_EXEMPLAR_SHARED_LIBS=OFF -DBEMAN_SHARED_LIBS=ON -DSHARED_LIBS=ON
            expected-variant: static
            expected-library: .a
          - description: Beman-specific shared libs option has second priority
            config: -DBEMAN_SHARED_LIBS=ON -DBUILD_SHARED_LIBS=OFF
            expected-variant: shared
            expected-library: .so
          - description: Beman-specific shared libs option has second priority
            config: -DBEMAN_SHARED_LIBS=OFF -DBUILD_SHARED_LIBS=ON
            expected-variant: static
            expected-library: .a
          - description: CMake shared libs option has third priority
            config: -DBUILD_SHARED_LIBS=ON
            expected-variant: shared
            expected-library: .so
          - description: CMake shared libs option has third priority
            config: -DBUILD_SHARED_LIBS=OFF
            expected-variant: static
            expected-library: .a
          - description: When building a static library, project-specific PIC option has first priority.
            config: -DBEMAN_EXEMPLAR_POSITION_INDEPENDENT_CODE=ON -DBEMAN_POSITION_INDEPENDENT_CODE=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=OFF
            expected-variant: static-pic
            expected-library: .pic.a
          - description: When building a static library, project-specific PIC option has first priority.
            config: -DBEMAN_EXEMPLAR_POSITION_INDEPENDENT_CODE=OFF -DBEMAN_POSITION_INDEPENDENT_CODE=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
            expected-variant: static
            expected-library: .a
          - description: When building a static library, Beman-specific PIC option has second priority.
            config: -DBEMAN_POSITION_INDEPENDENT_CODE=ON -DCMAKE_POSITION_INDEPENDENT_CODE=OFF
            expected-variant: static-pic
            expected-library: .pic.a
          - description: When building a static library, Beman-specific PIC option has second priority.
            config: -DBEMAN_POSITION_INDEPENDENT_CODE=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
            expected-variant: static
            expected-library: .a
          - description: When building a static library, CMake PIC option has third priority.
            config: -DCMAKE_POSITION_INDEPENDENT_CODE=ON
            expected-variant: static-pic
            expected-library: .pic.a
          - description: When building a static library, CMake PIC option has third priority.
            config: -DCMAKE_POSITION_INDEPENDENT_CODE=OFF
            expected-variant: static
            expected-library: .a
          - description: Explicit project-specific target export variant has the highest priority.
            config: -DBEMAN_EXEMPLAR_TARGET_EXPORT_VARIANT=custom -DBEMAN_TARGET_EXPORT_VARIANT=unused
            expected-variant: custom
            expected-library: .custom.a
          - description: Explicit Beman-specific target export variant has the second-highest priority.
            config: -DBEMAN_TARGET_EXPORT_VARIANT=custom -DBEMAN_POSITION_INDEPENDENT_CODE=ON -DBEMAN_LIBRARY_SUFFIX=.custom.pic
            expected-variant: custom
            expected-library: .custom.pic.a
    name: "Target Export Variant: ${{ matrix.cases.description }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
      - name: Print installed softwares
        run: |
          cmake --version
          ninja --version
      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_CXX_STANDARD=17 -DBEMAN_BUILD_TESTS=OFF -DBEMAN_BUILD_EXAMPLES=OFF -DBEMAN_BUILD_DOCS=OFF ${{ matrix.cases.config }}
        env:
          CMAKE_GENERATOR: "Ninja Multi-Config"
      - name: Build Release
        run: |
          # Portable commands only
          cmake --build build --config Release --parallel --verbose
          cmake --build build --config Release --target all_verify_interface_header_sets
          cmake --install build --config Release --prefix /opt/beman.exemplar

          if test ${{ matrix.cases.expected-variant }} = shared; then
            test -L /opt/beman.exemplar/lib/libbeman.exemplar${{ matrix.cases.expected-library }}
          else
            test -f /opt/beman.exemplar/lib/libbeman.exemplar${{ matrix.cases.expected-library }}
          fi

          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-config.cmake
          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-version.cmake
          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-${{ matrix.cases.expected-variant }}-target-export.cmake
          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-${{ matrix.cases.expected-variant }}-target-export-release.cmake
      - name: Build Debug
        run: |
          # Portable commands only
          cmake --build build --config Debug --parallel --verbose
          cmake --build build --config Debug --target all_verify_interface_header_sets
          cmake --install build --config Debug --prefix /opt/beman.exemplar

          if test ${{ matrix.cases.expected-variant }} = shared; then
            test -L /opt/beman.exemplar/lib/debug/libbeman.exemplar${{ matrix.cases.expected-library }}
          else
            test -f /opt/beman.exemplar/lib/debug/libbeman.exemplar${{ matrix.cases.expected-library }}
          fi

          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-config.cmake
          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-version.cmake
          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-${{ matrix.cases.expected-variant }}-target-export.cmake
          test -f /opt/beman.exemplar/lib/cmake/beman.exemplar/beman.exemplar-${{ matrix.cases.expected-variant }}-target-export-debug.cmake

  compiler-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        compilers:
          - class: GNU
            version: 14
          - class: GNU
            version: 13
          - class: GNU
            version: 12
          - class: LLVM
            version: 20
          - class: LLVM
            version: 19
          - class: LLVM
            version: 18
          - class: LLVM
            version: 17
    name: "Compiler: ${{ matrix.compilers.class }} ${{ matrix.compilers.version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Setup build environment
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.25.0"
          ninjaVersion: "^1.11.1"
      - name: Install Compiler
        id: install-compiler
        run: |
          if [ "${{ matrix.compilers.class }}" = "GNU" ]; then
            CC=gcc-${{ matrix.compilers.version }}
            CXX=g++-${{ matrix.compilers.version }}

            sudo add-apt-repository universe
            sudo apt-get update
            sudo apt-get install -y $CC
            sudo apt-get install -y $CXX

            $CC --version
            $CXX --version
          else
            wget https://apt.llvm.org/llvm.sh
            chmod +x llvm.sh
            sudo bash llvm.sh ${{ matrix.compilers.version }}

            CC=clang-${{ matrix.compilers.version }}
            CXX=clang++-${{ matrix.compilers.version }}

            $CC --version
            $CXX --version
          fi

          echo "CC=$CC" >> "$GITHUB_OUTPUT"
          echo "CXX=$CXX" >> "$GITHUB_OUTPUT"
      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_CXX_STANDARD=20
        env:
          CC: ${{ steps.install-compiler.outputs.CC }}
          CXX: ${{ steps.install-compiler.outputs.CXX }}
          CMAKE_GENERATOR: "Ninja Multi-Config"
      - name: Build Debug
        run: |
          cmake --build build --config Debug --verbose
          cmake --build build --config Debug --target all_verify_interface_header_sets
          cmake --install build --config Debug --prefix /opt/beman.exemplar
          find /opt/beman.exemplar -type f
      - name: Test Debug
        run: ctest --test-dir build --build-config Debug

  create-issue-when-fault:
    runs-on: ubuntu-latest
    needs: [preset-test, gtest-test, configuration-test, compiler-test]
    if: failure() && github.event_name == 'schedule'
    steps:
      # See https://github.com/cli/cli/issues/5075
      - uses: actions/checkout@v4
      - name: Create issue
        run: |
          issue_num=$(gh issue list -s open -S "[SCHEDULED-BUILD] Build & Test failure" -L 1 --json number | jq 'if length == 0 then -1 else .[0].number end')

          body="**Build-and-Test Failure Report**
          - **Time of Failure**: $(date -u '+%B %d, %Y, %H:%M %Z')
          - **Commit**: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          - **Action Run**: [View logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          The scheduled build-and-test triggered by cron has failed.
          Please investigate the logs and recent changes associated with this commit or rerun the workflow if you believe this is an error."

          if [[ $issue_num -eq -1 ]]; then
            gh issue create --repo ${{ github.repository }} --title "[SCHEDULED-BUILD] Build & Test failure" --body "$body"
          else
            gh issue comment --repo ${{ github.repository }} $issue_num --body "$body"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
